import json
import os
import sys

# Add lite package path
from pathlib import Path
from typing import Any, List, Literal, Optional

from pydantic import BaseModel, Field, field_validator

project_root = Path(__file__).resolve().parent.parent.parent.parent.parent
if str(project_root) not in sys.path:
    sys.path.append(str(project_root))

try:
    from lite import LiteClient
    from lite.config import ModelConfig, ModelInput
except ImportError:
    LiteClient = None
    ModelConfig = None
    ModelInput = None


# ---- Canonical edge (relation) types ----
Relation = Literal[
    "has_symptom",
    "caused_by",
    "risk_factor_for",
    "treated_with",
    "diagnosed_by",
    "leads_to",
    "associated_with",
    "prevented_by",
    "affects_system",
    "affects_organ",
    "complication_of",
    "other",
]

# ---- Node (entity) types ----
NodeType = Literal[
    "Disease",
    "Symptom",
    "Cause",
    "RiskFactor",
    "Treatment",
    "Drug",
    "Test",
    "BodySystem",
    "Organ",
    "Complication",
    "Prevention",
    "Condition",
    "Other",
]

# ---- Aliases for normalization ----
RELATION_ALIASES = {
    "symptom": "has_symptom",
    "shows": "has_symptom",
    "results_from": "caused_by",
    "caused": "caused_by",
    "risk": "risk_factor_for",
    "risk_factor": "risk_factor_for",
    "factor": "risk_factor_for",
    "treatment": "treated_with",
    "treated_by": "treated_with",
    "managed_by": "treated_with",
    "diagnosis": "diagnosed_by",
    "diagnosed_with": "diagnosed_by",
    "lead_to": "leads_to",
    "complication": "complication_of",
    "associated": "associated_with",
    "prevented_with": "prevented_by",
    "affects": "affects_system",
    "affects_organ": "affects_organ",
}

NODE_TYPE_ALIASES = {
    "disease": "Disease",
    "condition": "Condition",
    "symptom": "Symptom",
    "sign": "Symptom",
    "cause": "Cause",
    "factor": "RiskFactor",
    "risk": "RiskFactor",
    "treatment": "Treatment",
    "therapy": "Treatment",
    "drug": "Drug",
    "medicine": "Drug",
    "test": "Test",
    "examination": "Test",
    "system": "BodySystem",
    "organ": "Organ",
    "complication": "Complication",
    "prevention": "Prevention",
}


class Triple(BaseModel):
    """Represents one disease knowledge triple."""

    source: str = Field(..., description="Subject entity")
    relation: Relation = Field(..., description="Relation type")
    target: str = Field(..., description="Object entity")
    source_type: NodeType = "Other"
    target_type: NodeType = "Other"
    confidence: Optional[float] = None

    @field_validator("source", "target")
    @classmethod
    def not_empty_entity(cls, v: str) -> str:
        if not v or not v.strip():
            raise ValueError("Entity name cannot be empty")
        return v.strip()

    @field_validator("relation", mode="before")
    @classmethod
    def normalize_relation(cls, v: Any) -> str:
        if not v:
            return "other"
        rv = str(v).strip().lower().replace(" ", "_")
        if rv in RELATION_ALIASES:
            rv = RELATION_ALIASES[rv]
        allowed = set(Relation.__args__)
        return rv if rv in allowed else "other"

    @field_validator("source_type", "target_type", mode="before")
    @classmethod
    def normalize_node_type(cls, v: Any) -> str:
        if not v:
            return "Other"
        key = str(v).strip().lower().replace(" ", "_")
        if key.capitalize() in NodeType.__args__:
            return key.capitalize()
        if key in NODE_TYPE_ALIASES:
            return NODE_TYPE_ALIASES[key]
        return "Other"


class DiseaseReport(BaseModel):
    """Full structured disease report generated by LLM."""

    name: str = Field(..., description="Name of the disease")
    description: str = Field(..., description="High-level medical description")
    triples: List[Triple] = Field(..., description="List of knowledge triples")


# =========================
# 2️⃣ Disease Graph Builder
# =========================
class DiseaseKnowledgeGraphBuilder:
    """Builds and queries the disease knowledge graph using LLM."""

    def __init__(self, model_config: Optional["ModelConfig"] = None):
        self.nodes = {}  # name -> type
        self.edges = []  # List of dicts
        self.model_config = model_config
        self.client = None
        self.last_report = None

        if LiteClient is not None:
            if self.model_config is None:
                self.model_config = ModelConfig(model="ollama/gemma3", temperature=0.0)
            self.client = LiteClient(model_config=self.model_config)
        else:
            print("⚠️ 'lite' package not installed. Using offline mode.")

    def build_from_name(self, disease_name: str):
        """Generates a structured disease report and builds the graph."""
        if not self.client:
            print("⚠️ Using offline mode (No LiteClient).")
            return self._simulate(disease_name)

        system_prompt = (
            f"You are an expert medical knowledge extractor for the disease: {disease_name}.\n"
            "Produce knowledge triples following these EXACT directions:\n"
            f"- {disease_name} -> has_symptom -> [Symptom]\n"
            f"- {disease_name} -> caused_by -> [Pathogen/Cause]\n"
            f"- {disease_name} -> treated_with -> [Drug/Treatment]\n"
            f"- [Complication] -> complication_of -> {disease_name}\n"
            "- [Pathogen] -> source_type MUST be 'Cause'\n"
            "- [Symptom] -> source_type MUST be 'Symptom'\n"
            "DO NOT use medical authorities as sources. Use only the disease or its components."
        )

        model_input = ModelInput(
            system_prompt=system_prompt,
            user_prompt=disease_name,
            response_format=DiseaseReport,
        )

        try:
            report = self.client.generate_text(model_input=model_input)
            self.last_report = report
            self.add_triples(report.triples)
            return report.triples
        except Exception as e:
            print(f"⚠️ LLM Error: {e}. Falling back to simulation.")
            return self._simulate(disease_name)

    def add_triples(self, triples: List[Triple]):
        for t in triples:
            self.nodes[t.source] = t.source_type
            self.nodes[t.target] = t.target_type
            self.edges.append(
                {
                    "source": t.source,
                    "target": t.target,
                    "relation": t.relation,
                    "confidence": t.confidence,
                }
            )

    def _simulate(self, disease_name: str) -> List[Triple]:
        """Offline simulation for testing or fallback."""
        t = disease_name.lower()
        data = []
        if "malaria" in t:
            data = [
                Triple(
                    source="Malaria",
                    relation="has_symptom",
                    target="Fever",
                    source_type="Disease",
                    target_type="Symptom",
                ),
                Triple(
                    source="Malaria",
                    relation="caused_by",
                    target="Plasmodium",
                    source_type="Disease",
                    target_type="Cause",
                ),
            ]
        elif "diabetes" in t:
            data = [
                Triple(
                    source="Diabetes",
                    relation="has_symptom",
                    target="Thirst",
                    source_type="Disease",
                    target_type="Symptom",
                ),
                Triple(
                    source="Diabetes",
                    relation="treated_with",
                    target="Insulin",
                    source_type="Disease",
                    target_type="Drug",
                ),
            ]
        else:
            data = [
                Triple(
                    source=disease_name,
                    relation="associated_with",
                    target="Unknown",
                    source_type="Disease",
                    target_type="Other",
                )
            ]

        self.add_triples(data)
        return data

    def query_symptoms(self, disease: str):
        return [
            e["target"]
            for e in self.edges
            if e["source"].lower() == disease.lower() and e["relation"] == "has_symptom"
        ]

    def query_treatments(self, disease: str):
        return [
            e["target"]
            for e in self.edges
            if e["source"].lower() == disease.lower()
            and e["relation"] == "treated_with"
        ]

    def export_json(self, path: str = "disease_graph.json"):
        if self.last_report:
            with open(path, "w", encoding="utf-8") as f:
                f.write(self.last_report.model_dump_json(indent=2))
        else:
            triples = [
                {
                    "source": e["source"],
                    "relation": e["relation"],
                    "target": e["target"],
                    "source_type": self.nodes.get(e["source"]),
                    "target_type": self.nodes.get(e["target"]),
                    "confidence": e.get("confidence"),
                }
                for e in self.edges
            ]
            with open(path, "w", encoding="utf-8") as f:
                json.dump(triples, f, indent=2)
        print(f"✅ Graph exported to {path}")

    def export_dot(self, disease_name: str, folder: str = "outputs"):
        """Exports the graph to a DOT file for visualization."""
        os.makedirs(folder, exist_ok=True)
        filename = f"{disease_name.lower().replace(' ', '_')}.dot"
        path = os.path.join(folder, filename)

        color_map = {
            "Disease": "#fb8072",
            "Symptom": "#ffffb3",
            "RiskFactor": "#8dd3c7",
            "Treatment": "#bebada",
            "Drug": "#80b1d3",
            "Test": "#bebada",
            "Organ": "#ccebc5",
            "Complication": "#fdb462",
            "Prevention": "#b3de69",
            "Other": "#d9d9d9",
        }

        dot_lines = [
            "digraph G {",
            "    rankdir=LR;",
            '    node [shape=box, style=filled, fontname="Arial"];',
        ]

        # Add nodes with colors
        for node, ntype in self.nodes.items():
            color = color_map.get(ntype, "#d9d9d9")
            label = f"{node}\\n({ntype})"
            dot_lines.append(f'    "{node}" [fillcolor="{color}", label="{label}"];')

        # Add edges
        for e in self.edges:
            dot_lines.append(
                f'    "{e["source"]}" -> "{e["target"]}" [label="{e["relation"]}"];'
            )

        dot_lines.append("}")

        with open(path, "w", encoding="utf-8") as f:
            f.write("\n".join(dot_lines))
        print(f"✅ Graph exported to {path}")


# =========================
# 3️⃣ Visualization
# =========================
class GraphVisualizer:
    """Prints the disease knowledge graph (Simplified without NetworkX/Matplotlib)."""

    def __init__(self, builder: DiseaseKnowledgeGraphBuilder):
        self.builder = builder

    def show(self):
        print("\n--- Disease Knowledge Graph ---")
        for e in self.builder.edges:
            print(
                f"({e['source']}: {self.builder.nodes.get(e['source'])}) --[{e['relation']}]--> ({e['target']}: {self.builder.nodes.get(e['target'])})"
            )


class ModelOutput(BaseModel):
    """Standardized artifact envelope for the application."""
    data: Optional[Any] = None      # Tier 1: Specialists Facts (JSON Object)
    markdown: Optional[str] = None  # Tier 3: Final Synthesized Report (Markdown String)
    metadata: Optional[dict] = Field(default_factory=dict) # Tier 2: Process Artifacts (Audit/Reasoning)
