"""
liteagents.py - Unified LiteClient-based agents for Riemann.
"""

from app.Riemann.shared.models import *
from app.Riemann.shared.prompts import PromptBuilder
from app.Riemann.shared.utils import *
from lite import logging_config
from lite.config import ModelConfig, ModelInput
from lite.lite_client import LiteClient
from pathlib import Path
from pydantic import BaseModel, Field
from typing import Any
from typing import List
from typing import Optional, List
from typing import Optional, List, Dict, Any
import asyncio
import json
import logging
import os

"""
Pydantic models for the Multi-Agent Riemann Theory Guide.
"""

class RiemannOverviewModel(BaseModel):
    """Pedagogical and narrative data generated by the Overview Agent."""
    name: str = Field(description="Name of the Riemann theory or concept")
    layperson_explanation: str = Field(description="A simple, non-mathematical explanation for a layperson")
    intuition: str = Field(description="The 'bigger picture' and intuitive explanation")
    historical_context: str = Field(description="History and origin of the theory")
    motivation: str = Field(description="Specific problems Riemann was trying to solve")

class RiemannTechnicalModel(BaseModel):
    """Rigorous mathematical data generated by the Technical Agent."""
    definition: str = Field(description="Formal mathematical or conceptual definition")
    misconceptions: List[str] = Field(description="Common myths and the reality behind them")
    limitations: str = Field(description="Boundaries and unsolved obstacles")
    modern_developments: str = Field(description="How the theory has progressed since Riemann")
    key_properties: List[str] = Field(description="Key mathematical properties")
    related_concepts: List[str] = Field(description="Related mathematical concepts")

class RiemannAppliedImpactModel(BaseModel):
    """Real-world impact data generated by the Application Expert Agent."""
    applications: List[str] = Field(description="Practical or theoretical applications in science/tech")
    significance: str = Field(description="Broad significance in modern science")
    counterfactual_impact: str = Field(description="How the world would be different if this wasn't developed")

class RiemannTheoryModel(RiemannOverviewModel, RiemannTechnicalModel, RiemannAppliedImpactModel):
    """The final unified Riemann Theory dossier."""
    pass

class ModelOutput(BaseModel):
    """Standardized artifact envelope for the application."""
    data: Optional[Any] = None      # Tier 1: Specialists Facts (JSON Object)
    markdown: Optional[str] = None  # Tier 3: Final Synthesized Report (Markdown String)
    metadata: Optional[dict] = Field(default_factory=dict) # Tier 2: Process Artifacts (Audit/Reasoning)

#!/usr/bin/env python3
"""
Riemann Theory Reference Guide
Dynamically fetches and documents Riemann-related mathematical theories and concepts,
using LiteClient (ollama/gemma3) for current and comprehensive information.
"""

try:
    from app.Riemann.shared.models import RiemannTheoryModel, ModelOutput
    from app.Riemann.shared.prompts import PromptBuilder
except ImportError:
    import sys

    sys.path.insert(0, str(Path(__file__).parent))
    from riemann_problems_models import RiemannTheoryModel, ModelOutput
    from riemann_problems_prompts import PromptBuilder

# Setup logging
logging_config.configure_logging(str(Path(__file__).parent / "logs" / "riemann_theory.log"))
logger = logging.getLogger(__name__)

class RiemannTheoryGuide:
    """Reference guide for various Riemann theories using LiteClient."""

    def __init__(self, config: Optional[ModelConfig] = None):
        """
        Initialize the guide with API client.

        Args:
            config: Optional ModelConfig. If not provided, uses sensible defaults.
        """
        self.config = config or ModelConfig(model="ollama/gemma3", temperature=0.3)
        self.client = LiteClient(self.config)
        self.theories_file = Path(__file__).parent.parent / "assets" / "riemann.txt"
        self.available_theories = self._load_theories()

    def _load_theories(self) -> List[str]:
        """Load available theories from the assets file."""
        try:
            if self.theories_file.exists():
                with open(self.theories_file, "r") as f:
                    return [line.strip() for line in f if line.strip()]
            else:
                logger.warning(f"Theories file not found: {self.theories_file}")
                return []
        except Exception as e:
            logger.error(f"Error loading theories: {str(e)}")
            return []

    def generate_text(self, theory_name: str) -> Optional[ModelOutput]:
        """
        Fetch information for a specific Riemann theory using a 3-tier approach.

        Args:
            theory_name: Name of the theory or concept

        Returns:
            ModelOutput instance or None if fetch fails
        """
        try:
            logger.info(f"Fetching 3-tier Riemann theory '{theory_name}' from API")

            # Tier 1: Specialist (JSON)
            model_input = ModelInput(
                system_prompt=PromptBuilder.get_system_prompt(),
                user_prompt=PromptBuilder.get_user_prompt(theory_name),
                response_format=RiemannTheoryModel
            )
            theory_res = self.client.generate_text(model_input)
            theory_data: RiemannTheoryModel = theory_res.data

            # Tier 3: Output Synthesis (Markdown Closer)
            # In this simple app, we can use the LLM to generate a nice narrative from the data
            synth_prompt = f"Synthesize a beautiful Markdown reference report for the theory: {theory_name}\n\nDATA:\n{theory_data.model_dump_json(indent=2)}"
            synth_input = ModelInput(
                system_prompt="You are a Lead Mathematical Editor. Synthesize raw theory data into a professional Markdown report.",
                user_prompt=synth_prompt,
                response_format=None
            )
            final_markdown = self.client.generate_text(synth_input).markdown

            logger.info(f"Successfully synthesized theory: {theory_name}")
            return ModelOutput(
                data=theory_data,
                markdown=final_markdown,
                metadata={"process": "2-stage fetch-and-synthesize"}
            )

        except Exception as e:
            logger.error(f"Error fetching theory '{theory_name}': {str(e)}")
            return None

    def save_to_file(self, output: ModelOutput, theory_name: str, output_dir: str) -> str:
        """
        Save a Riemann theory artifact to Markdown and JSON.
        """
        try:
            output_path = Path(output_dir)
            output_path.mkdir(parents=True, exist_ok=True)
            
            safe_name = theory_name.lower().replace(' ', '_').replace('/', '_').replace(':', '_')
            md_path = output_path / f"riemann_{safe_name}.md"
            json_path = output_path / f"riemann_{safe_name}.json"
            
            if output.markdown:
                with open(md_path, 'w', encoding='utf-8') as f:
                    f.write(output.markdown)
            
            if output.data:
                with open(json_path, 'w', encoding='utf-8') as f:
                    f.write(output.data.model_dump_json(indent=4))
            
            logger.info(f"Saved theory artifact '{theory_name}' to {output_dir}")
            return str(md_path)
            
        except Exception as e:
            logger.error(f"Error saving theory '{theory_name}': {str(e)}")
            raise

    @staticmethod
    def display_theory(output: ModelOutput):
        """Display synthesized information about a Riemann theory."""
        if not output or not output.markdown:
            print("\n❌ Error: No theory information available.")
            return

        print(f"\n{output.markdown}\n")

    def display_summary(self):
        """Display a summary of available Riemann theories."""
        print(f"\n{'='*80}")
        print("SUMMARY OF RIEMANN THEORIES AND CONCEPTS")
        print(f"{'='*80}")
        
        if not self.available_theories:
            print("\n❌ Error: No theories found in assets.")
            return

        print(f"\nFound {len(self.available_theories)} theories in assets/riemann.txt.")
        print("\nFetching overview information from AI...")
        
        try:
            user_prompt = PromptBuilder.get_summary_prompt(self.available_theories)
            model_input = ModelInput(
                system_prompt=PromptBuilder.get_system_prompt(),
                user_prompt=user_prompt
            )
            summary_text = self.client.generate_text(model_input).markdown
            print(f"\n{summary_text}")
        except Exception as e:
            logger.error(f"Error fetching summary: {str(e)}")
            print(f"\n❌ Error fetching summary: {str(e)}")
        
        print(f"\n{'='*80}\n")

try:
    from app.Riemann.shared.models import (
        RiemannTheoryModel,
        RiemannOverviewModel,
        RiemannTechnicalModel,
        RiemannAppliedImpactModel,
    )
    from app.Riemann.shared.prompts import AgentPersonas, PromptBuilder
except ImportError:
    import sys

    sys.path.insert(0, str(Path(__file__).parent))
    from riemann_problems_models import (
        RiemannTheoryModel,
        RiemannOverviewModel,
        RiemannTechnicalModel,
        RiemannAppliedImpactModel,
    )
    from riemann_problems_prompts import AgentPersonas, PromptBuilder

class MultiAgentRiemannGuide:
    """
    Orchestrates 5 specialized agents:
    1. Researcher (History)
    2. Overview (Pedagogical Narrative)
    3. Technical (Mathematical Formalism)
    4. Application Expert (Real-world Impact)
    5. Critic (Integration & Quality Control)
    """

    def __init__(self, model: str = "ollama/gemma3"):
        self.config = ModelConfig(model=model, temperature=0.1)
        self.client = LiteClient(self.config)

    async def researcher_agent(self, theory_name: str) -> str:
        print(f"🕵️  Researcher Agent: Fact-checking {theory_name}...")
        model_input = ModelInput(
            system_prompt=AgentPersonas.get_researcher_prompt(),
            user_prompt=f"Provide a research brief for: '{theory_name}'."
        )
        return self.client.generate_text(model_input)

    async def overview_agent(self, theory_name: str, brief: str) -> RiemannOverviewModel:
        print(f"🏫 Overview Agent (Teacher): Drafting narrative for {theory_name}...")
        model_input = ModelInput(
            system_prompt=AgentPersonas.get_overview_prompt(),
            user_prompt=f"Create a pedagogical overview for '{theory_name}' based on this brief:\n{brief}",
            response_format=RiemannOverviewModel
        )
        return self.client.generate_text(model_input)

    async def technical_agent(self, theory_name: str, brief: str) -> RiemannTechnicalModel:
        print(f"🎓 Technical Agent (Professor): Drafting formal math for {theory_name}...")
        model_input = ModelInput(
            system_prompt=AgentPersonas.get_technical_prompt(),
            user_prompt=f"Create a rigorous mathematical core for '{theory_name}' based on this brief:\n{brief}",
            response_format=RiemannTechnicalModel
        )
        return self.client.generate_text(model_input)

    async def app_expert_agent(self, theory_name: str, tech_report: RiemannTechnicalModel) -> RiemannAppliedImpactModel:
        print(f"🚀 Application Expert: Analyzing impact of {theory_name}...")
        tech_data = tech_report.model_dump_json()
        model_input = ModelInput(
            system_prompt=AgentPersonas.get_app_expert_prompt(),
            user_prompt=f"Explain applications for '{theory_name}' given this math:\n{tech_data}",
            response_format=RiemannAppliedImpactModel
        )
        return self.client.generate_text(model_input)

    async def critic_agent(self, theory_name: str, overview: RiemannOverviewModel, technical: RiemannTechnicalModel, applied: RiemannAppliedImpactModel) -> str:
        print(f"🧐 Critic Agent: Synthesizing final Markdown dossier for {theory_name}...")
        dossier_data = {
            "theory": theory_name,
            "overview": overview.model_dump(),
            "technical": technical.model_dump(),
            "applied": applied.model_dump()
        }
        model_input = ModelInput(
            system_prompt=AgentPersonas.get_critic_prompt(),
            user_prompt=f"Review and synthesize this dossier data into a final Markdown report:\n{json.dumps(dossier_data, indent=2)}"
        )
        return self.client.generate_text(model_input)

    async def run_pipeline(self, theory_name: str) -> str:
        # 1. Fact-finding
        brief = await self.researcher_agent(theory_name)
        
        # 2. Parallelizable Creation
        overview = await self.overview_agent(theory_name, brief)
        technical = await self.technical_agent(theory_name, brief)
        
        # 3. Contextual Application Analysis
        applied = await self.app_expert_agent(theory_name, technical)
        
        # 4. Peer Review & Synthesis
        final_markdown = await self.critic_agent(theory_name, overview, technical, applied)
            
        print(f"✅ 5-Agent dossier complete for '{theory_name}'.")
        return final_markdown

async def run_riemann_agent(theory_name: str, model: str = "ollama/gemma3") -> str:
    orchestrator = MultiAgentRiemannGuide(model=model)
    return await orchestrator.run_pipeline(theory_name)

