"""
Pydantic models for the Multi-Agent Riemann Theory Guide.
"""

from typing import List
from pydantic import BaseModel, Field


class RiemannOverviewModel(BaseModel):
    """Pedagogical and narrative data generated by the Overview Agent."""
    name: str = Field(description="Name of the Riemann theory or concept")
    layperson_explanation: str = Field(description="A simple, non-mathematical explanation for a layperson")
    intuition: str = Field(description="The 'bigger picture' and intuitive explanation")
    historical_context: str = Field(description="History and origin of the theory")
    motivation: str = Field(description="Specific problems Riemann was trying to solve")


class RiemannTechnicalModel(BaseModel):
    """Rigorous mathematical data generated by the Technical Agent."""
    definition: str = Field(description="Formal mathematical or conceptual definition")
    misconceptions: List[str] = Field(description="Common myths and the reality behind them")
    limitations: str = Field(description="Boundaries and unsolved obstacles")
    modern_developments: str = Field(description="How the theory has progressed since Riemann")
    key_properties: List[str] = Field(description="Key mathematical properties")
    related_concepts: List[str] = Field(description="Related mathematical concepts")


class RiemannAppliedImpactModel(BaseModel):
    """Real-world impact data generated by the Application Expert Agent."""
    applications: List[str] = Field(description="Practical or theoretical applications in science/tech")
    significance: str = Field(description="Broad significance in modern science")
    counterfactual_impact: str = Field(description="How the world would be different if this wasn't developed")


class RiemannTheoryModel(RiemannOverviewModel, RiemannTechnicalModel, RiemannAppliedImpactModel):
    """The final unified Riemann Theory dossier."""
    pass


from typing import Any

class ModelOutput(BaseModel):
    """Standardized artifact envelope for the application."""
    data: Optional[Any] = None      # Tier 1: Specialists Facts (JSON Object)
    markdown: Optional[str] = None  # Tier 3: Final Synthesized Report (Markdown String)
    metadata: Optional[dict] = Field(default_factory=dict) # Tier 2: Process Artifacts (Audit/Reasoning)
